/**
 * @fileoverview Error templates for HTTP status codes
 * Mirrored from sdp-ai project for consistency
 */
export const ErrorTemplates = {
  CONTINUE: { status: 100, code: "CONTINUE" },
  SWITCHING_PROTOCOLS: { status: 101, code: "SWITCHING_PROTOCOLS" },
  PROCESSING: { status: 102, code: "PROCESSING" },
  OK: { status: 200, code: "OK" },
  CREATED: { status: 201, code: "CREATED" },
  ACCEPTED: { status: 202, code: "ACCEPTED" },
  NON_AUTHORITATIVE_INFORMATION: {
    status: 203,
    code: "NON_AUTHORITATIVE_INFORMATION",
  },
  NO_CONTENT: { status: 204, code: "NO_CONTENT" },
  RESET_CONTENT: { status: 205, code: "RESET_CONTENT" },
  PARTIAL_CONTENT: { status: 206, code: "PARTIAL_CONTENT" },
  MULTI_STATUS: { status: 207, code: "MULTI_STATUS" },
  ALREADY_REPORTED: { status: 208, code: "ALREADY_REPORTED" },
  IM_USED: { status: 226, code: "IM_USED" },
  MULTIPLE_CHOICES: { status: 300, code: "MULTIPLE_CHOICES" },
  MOVED_PERMANENTLY: { status: 301, code: "MOVED_PERMANENTLY" },
  FOUND: { status: 302, code: "FOUND" },
  SEE_OTHER: { status: 303, code: "SEE_OTHER" },
  NOT_MODIFIED: { status: 304, code: "NOT_MODIFIED" },
  USE_PROXY: { status: 305, code: "USE_PROXY" },
  SWITCH_PROXY: { status: 306, code: "SWITCH_PROXY" },
  TEMPORARY_REDIRECT: { status: 307, code: "TEMPORARY_REDIRECT" },
  PERMANENT_REDIRECT: { status: 308, code: "PERMANENT_REDIRECT" },
  BAD_REQUEST: { status: 400, code: "BAD_REQUEST" },
  username: { status: 400, code: "username" },
  password: { status: 400, code: "PASSWORD" },
  USER_NOT_FOUND: { status: 400, code: "USER_NOT_FOUND" },
  UNAUTHORIZED: { status: 401, code: "UNAUTHORIZED" },
  PAYMENT_REQUIRED: { status: 402, code: "PAYMENT_REQUIRED" },
  FORBIDDEN: { status: 403, code: "FORBIDDEN" },
  NOT_FOUND: { status: 404, code: "NOT_FOUND" },
  METHOD_NOT_ALLOWED: { status: 405, code: "METHOD_NOT_ALLOWED" },
  NOT_ACCEPTABLE: { status: 406, code: "NOT_ACCEPTABLE" },
  PROXY_AUTHENTICATION_REQUIRED: {
    status: 407,
    code: "PROXY_AUTHENTICATION_REQUIRED",
  },
  REQUEST_TIMEOUT: { status: 408, code: "REQUEST_TIMEOUT" },
  CONFLICT: { status: 409, code: "CONFLICT" },
  GONE: { status: 410, code: "GONE" },
  LENGTH_REQUIRED: { status: 411, code: "LENGTH_REQUIRED" },
  PRECONDITION_FAILED: { status: 412, code: "PRECONDITION_FAILED" },
  PAYLOAD_TOO_LARGE: { status: 413, code: "PAYLOAD_TOO_LARGE" },
  URI_TOO_LONG: { status: 414, code: "URI_TOO_LONG" },
  UNSUPPORTED_MEDIA_TYPE: { status: 415, code: "UNSUPPORTED_MEDIA_TYPE" },
  RANGE_NOT_SATISFIABLE: { status: 416, code: "RANGE_NOT_SATISFIABLE" },
  EXPECTATION_FAILED: { status: 417, code: "EXPECTATION_FAILED" },
  I_AM_A_TEAPOT: { status: 418, code: "I_AM_A_TEAPOT" },
  MISDIRECTED_REQUEST: { status: 421, code: "MISDIRECTED_REQUEST" },
  UNPROCESSABLE_ENTITY: { status: 422, code: "UNPROCESSABLE_ENTITY" },
  LOCKED: { status: 423, code: "LOCKED" },
  FAILED_DEPENDENCY: { status: 424, code: "FAILED_DEPENDENCY" },
  UPGRADE_REQUIRED: { status: 426, code: "UPGRADE_REQUIRED" },
  PRECONDITION_REQUIRED: { status: 428, code: "PRECONDITION_REQUIRED" },
  TOO_MANY_REQUESTS: { status: 429, code: "TOO_MANY_REQUESTS" },
  REQUEST_HEADER_FIELDS_TOO_LARGE: {
    status: 431,
    code: "REQUEST_HEADER_FIELDS_TOO_LARGE",
  },
  UNAVAILABLE_FOR_LEGAL_REASONS: {
    status: 451,
    code: "UNAVAILABLE_FOR_LEGAL_REASONS",
  },
  INTERNAL_SERVER_ERROR: { status: 500, code: "INTERNAL_SERVER_ERROR" },
  NOT_IMPLEMENTED: { status: 501, code: "NOT_IMPLEMENTED" },
  BAD_GATEWAY: { status: 502, code: "BAD_GATEWAY" },
  SERVICE_UNAVAILABLE: { status: 503, code: "SERVICE_UNAVAILABLE" },
  GATEWAY_TIMEOUT: { status: 504, code: "GATEWAY_TIMEOUT" },
  HTTP_VERSION_NOT_SUPPORTED: {
    status: 505,
    code: "HTTP_VERSION_NOT_SUPPORTED",
  },
  VARIANT_ALSO_NEGOTIATES: { status: 506, code: "VARIANT_ALSO_NEGOTIATES" },
  INSUFFICIENT_STORAGE: { status: 507, code: "INSUFFICIENT_STORAGE" },
  LOOP_DETECTED: { status: 508, code: "LOOP_DETECTED" },
  NOT_EXTENDED: { status: 510, code: "NOT_EXTENDED" },
  NETWORK_AUTHENTICATION_REQUIRED: {
    status: 511,
    code: "NETWORK_AUTHENTICATION_REQUIRED",
  },
} as const;

export type ErrorTemplate = typeof ErrorTemplates;
export type ErrorTemplateKey = keyof ErrorTemplate;
